#!/usr/bin/env bash
# calibrate_camera.sh — one-time, per-site: let the webcam's auto-exposure settle
# on a WELL-EXPOSED FACE in the kiosk's real lighting, then read back the values
# it chose and write them to /etc/fr-kiosk/camera.env for lock_camera.sh to pin.
#
# HOW TO USE (on the Pi, in the kiosk's actual mounted position + lighting):
#   1. Make sure the kiosk browser is NOT running (it holds the camera):
#        sudo systemctl stop fr-kiosk-chromium.service   # or close Firefox
#   2. Have a person stand where users stand, face lit as it will be in use.
#   3. Run:  sudo ./calibrate_camera.sh
#      It re-enables auto for a few seconds so the camera adapts to the face,
#      then freezes and records the settled values.
#   4. Review the printed camera.env, then apply with lock_camera.sh.
set -euo pipefail

OUT="${CAM_ENV:-/etc/fr-kiosk/camera.env}"
DEV="${FR_CAM_DEVICE:-}"
SETTLE_SECS="${FR_CAM_SETTLE:-5}"

command -v v4l2-ctl >/dev/null 2>&1 || {
    echo "calibrate: v4l2-ctl not found — sudo apt install v4l-utils" >&2; exit 1; }

# Reuse lock_camera's node-picking logic by finding a node with exposure ctrls.
if [ -z "$DEV" ]; then
    for d in /dev/video*; do
        [ -e "$d" ] || continue
        drv="$(v4l2-ctl -d "$d" -D 2>/dev/null | awk -F': *' '/Driver name/{print $2}')"
        if v4l2-ctl -d "$d" --list-ctrls 2>/dev/null | grep -qiE 'exposure'; then
            case "$drv" in *bcm2835*|*unicam*|*pispbe*) continue ;; esac
            DEV="$d"; break
        fi
    done
fi
[ -n "$DEV" ] || { echo "calibrate: no webcam node found" >&2; exit 1; }
echo "calibrate: using device $DEV"

CTRLS="$(v4l2-ctl -d "$DEV" --list-ctrls 2>/dev/null || true)"
resolve() { for n in "$@"; do echo "$CTRLS" | grep -qE "^[[:space:]]*${n}[[:space:]]" && { echo "$n"; return; }; done; echo ""; }
getval() { [ -n "$1" ] && v4l2-ctl -d "$DEV" --get-ctrl "$1" 2>/dev/null | awk -F': *' '{print $2}'; }

AE_CTRL="$(resolve auto_exposure exposure_auto)"
EXP_CTRL="$(resolve exposure_time_absolute exposure_absolute)"
GAIN_CTRL="$(resolve gain)"
WBA_CTRL="$(resolve white_balance_automatic white_balance_temperature_auto)"
WB_CTRL="$(resolve white_balance_temperature)"

echo "calibrate: enabling AUTO for ${SETTLE_SECS}s — keep a lit face in frame ..."
# UVC: 3 = Aperture Priority (auto exposure); 1 (white_balance auto) = on.
[ -n "$AE_CTRL" ]  && v4l2-ctl -d "$DEV" --set-ctrl "${AE_CTRL}=3"  2>/dev/null || true
[ -n "$WBA_CTRL" ] && v4l2-ctl -d "$DEV" --set-ctrl "${WBA_CTRL}=1" 2>/dev/null || true

# The camera only actually adapts while something is streaming from it. Pull a
# few seconds of frames so AE/AWB converge, then read the settled values.
v4l2-ctl -d "$DEV" --stream-mmap --stream-count=$(( SETTLE_SECS * 10 )) \
    --stream-to=/dev/null >/dev/null 2>&1 || sleep "$SETTLE_SECS"

EXPOSURE="$(getval "$EXP_CTRL")"
GAIN="$(getval "$GAIN_CTRL")"
WB="$(getval "$WB_CTRL")"

echo "calibrate: settled values -> exposure=${EXPOSURE:-?} gain=${GAIN:-?} wb=${WB:-?}"

TMP="$(mktemp)"
cat > "$TMP" <<EOF
# camera.env — calibrated V4L2 lock values for the kiosk webcam.
# Generated by calibrate_camera.sh on $(date -Iseconds) at device $DEV.
# Re-run calibration if the kiosk's lighting or mounting changes.
FR_CAM_DEVICE=$DEV
FR_CAM_EXPOSURE=${EXPOSURE}
FR_CAM_GAIN=${GAIN}
FR_CAM_WB=${WB}
EOF

echo "calibrate: proposed $OUT ----------------------------------------------"
cat "$TMP"
echo "-----------------------------------------------------------------------"
mkdir -p "$(dirname "$OUT")"
install -m 0644 "$TMP" "$OUT"
rm -f "$TMP"
echo "calibrate: wrote $OUT — review it, then run: sudo ./lock_camera.sh"
